{% set name = "robomimic" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robomimic-{{ version }}.tar.gz
  sha256: b60c1a196469f898a807258ea7943adcb52c6521777abae7fccf92b509f6490a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.13.3
    - h5py
    - psutil
    - tqdm
    - termcolor
    - tensorboard
    - tensorboardx
    - imageio
    - imageio-ffmpeg
    - matplotlib-base
    - egl-probe >=1.0.1
    - pytorch
    - torchvision

test:
  imports:
    - robomimic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ARISE-Initiative/robomimic
  summary: 'robomimic: A Modular Framework for Robot Learning from Demonstration'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
