{% set name = "robomimic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ARISE-Initiative/robomimic/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7377276b6b9fb12e211974f386faecb8e1a4838a07a157e4d50a00b621a458a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.13.3
    - h5py
    - psutil
    - tqdm
    - termcolor
    - tensorboard
    - tensorboardx
    - imageio
    - imageio-ffmpeg
    - matplotlib-base
    - egl-probe >=1.0.1
    - pytorch
    - torchvision
    - huggingface_hub

test:
  imports:
    - robomimic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ARISE-Initiative/robomimic
  summary: 'robomimic: A Modular Framework for Robot Learning from Demonstration'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - diegoferigo
